package me.geso.jtt.lexer;

public enum TokenType {
	PLUS, MINUS, DIVIDE, LPAREN, RPAREN, INTEGER, OPENTAG, CLOSETAG, MUL, END, SWITCH, CASE, WHILE, FOREACH, IF, ELSIF, ELSE, IDENT, CONCAT, DOUBLE, RAW, DOT, TRUE, FALSE, NULL, LBRACKET, RBRACKET, LBRACE, RBRACE, COMMA, ARROW, EQAULS, ASSIGN, STRING, MODULO, LT, LE, GT, GE, INCLUDE, WITH, LOOP, IN, SET, LAST, NEXT, QUESTION, KOLON
}
