package me.geso.jtt.parser;

public enum NodeType {
	INTEGER,
	STRING,
	VARNAME,
	RAW_STRING,
	EXPRESSION, TEMPLATE, ADD, IDENT, SUBTRACT, MULTIPLY, DIVIDE, DOUBLE, FOREACH, EQAULS, GT, GE, LE, LT, ARRAY, MODULO, IF, TRUE, FALSE, NULL, CONCAT, SET, WHILE, LAST, NEXT, INCLUDE, MAP, ATTRIBUTE, SWITCH, DEFAULT, CASE, RANGE, NOT, PIPE, FUNCALL, ANDAND, NE, OROR, DOLLARVAR
}
