package me.geso.jtt.parser;

public enum NodeType {
	INTEGER,
	STRING,
	RAW_STRING,
	EXPRESSION, TEMPLATE, ADD, IDENT, SUBTRACT, MULTIPLY, DIVIDE, DOUBLE, FOREACH, EQUALS, GT, GE, LE, LT, ARRAY, MODULO, IF, TRUE, FALSE, NULL, CONCAT, SET, WHILE, LAST, NEXT, INCLUDE, MAP, ATTRIBUTE, SWITCH, DEFAULT, CASE, RANGE, NOT, FUNCALL, ANDAND, NE, OROR, DOLLARVAR, WRAPPER, LOOP_COUNT, LOOP_HAS_NEXT, LOOP_INDEX
}
