package me.geso.jtt.vm;

public enum OP {
	LOAD_CONST, APPEND, ADD, RETURN, INVOKE, ELEM, LOAD_VAR, SUBTRACT, DIVIDE, MULTIPLY, FOREACH, GET_ITER, ITER_NEXT, ITER_START, FOR_ITER, SET_VAR, EQAULS, GE, GT, LE, LT, MAKE_ARRAY, MODULO, LOAD_FALSE, LOAD_TRUE, LOAD_NULL, JUMP_IF_FALSE, JUMP, CONCAT, LAST, JUMP_ABS, INCLUDE, ATTRIBUTE, MAKE_MAP, MATCH, LOAD_LVAR, SET_LVAR, FUNCALL, LC, UC, SPRINTF, URI_ESCAPE, MAKE_RANGE, NOT, METHOD_CALL, ANDAND, NE, OROR, GET, LOOP;
}
