package me.geso.jtt.vm;

public enum OP {
	LOAD_CONST, APPEND, ADD, RETURN, GET_ELEM, LOAD_VAR, SUBTRACT, DIVIDE, MULTIPLY, ITER_START, FOR_ITER, SET_VAR, EQUALS, GE, GT, LE, LT, MAKE_ARRAY, MODULO, LOAD_FALSE, LOAD_TRUE, LOAD_NULL, JUMP_IF_FALSE, JUMP, CONCAT, JUMP_ABS, INCLUDE, ATTRIBUTE, MAKE_MAP, MATCH, LOAD_LVAR, SET_LVAR, FUNCALL, LC, UC, SPRINTF, URI_ESCAPE, MAKE_RANGE, NOT, METHOD_CALL, ANDAND, NE, OROR, LOOP, WRAP, APPEND_RAW, LOAD_INT, MOVE;
}
